service: order-serverlessly

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  createOrder:
    handler: handler.createOrder
    events:
     - httpApi:
         path: /order
         method: post
    environment:
      orderTableName: orders
      orderStreamName: order-events

resources:
  Resources:
    ordersEventStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: order-events
        ShardCount: 1
    ordersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: orders
        AttributeDefinitions:
          - AttributeName: "orderId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "orderId"
            KeyType: "HASH"
        BillingMode: PAY_PER_REQUEST
